# Site 网站
# 网站标题
title: linjiad技术博客
#网站副标题
subtitle: 柳外轻雷池上雨，雨声滴碎荷声
#网站描述
description: 这个人很懒什么也没写
keywords:
#您的名字
author: linjiad
#网站使用的语言
language: JS
#网站时区。
timezone:

# URL 网址
#网址
url: http://linjiad.github.io
#网站根目录
root: /
#文章的 永久链接 格式 :year/:month/:day/:title/
permalink: :year/:month/:day/:title/
#永久链接中各部分的默认值
permalink_defaults:

# Directory 目录
# 资源文件夹，这个文件夹用来存放内容。
source_dir: source
# 公共文件夹，这个文件夹用于存放生成的站点文件。
public_dir: public
# 标签文件夹
tag_dir: tags
# 归档文件夹
archive_dir: archives
# 分类文件夹
category_dir: categories
# Include code 文件夹
code_dir: downloads/code
# 国际化（i18n）文件夹
i18n_dir: :lang
# 跳过指定文件的渲染，您可使用 glob 表达式来匹配路径
skip_render:

# Writing 文章
# 新文章的文件名称
new_post_name: :title.md # File name of new posts
#预设布局，以后就在source下的_post下查看文章
default_layout: post
#把标题转换为 title case
titlecase: false # Transform title into titlecase
#在新标签中打开链接
external_link: true # Open external links in new tab
#把文件名称转换为 (1) 小写或 (2) 大写
filename_case: 0
#显示草稿
render_drafts: false
#启动 Asset 文件夹
post_asset_folder: true
#把链接改为与根目录的相对位址
relative_link: false
#显示未来的文章
future: true
#代码块的设置
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting分页
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag 分类 & 标签、
# 默认分类
default_category: uncategorized
#分类别名
category_map:
#标签别名
tag_map:

# Date / Time format 日期 / 时间格式
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
#日期格式
date_format: YYYY-MM-DD
#时间格式
time_format: HH:mm:ss

# Pagination 分页
## Set per_page to 0 to disable pagination
#每页显示的文章量 (0 = 关闭分页功能)
per_page: 10
#分页目录
pagination_dir: page

# Extensions 扩展
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#当前主题名称。值为false时禁用主题
theme: tree

# Deployment
## Docs: https://hexo.io/docs/deployment.html
#部署部分的设置
deploy:
  type: git
  repo: https://linjiadweb:jkp66902@github.com/linjiadweb/linjiadweb.github.io.git
  branch: master
